# Crie um algoritmo que calcule tabuadas.
num = int(input('Digite o número que deseja ver a tabuada:'))
print('{} x {} = {}'.format(1, num, 1*num))
print('{} x {} = {}'.format(2, num, 2*num))
print('{} x {} = {}'.format(3, num, 3*num))
print('{} x {} = {}'.format(4, num, 4*num))
print('{} x {} = {}'.format(5, num, 5*num))
print('{} x {} = {}'.format(6, num, 6*num))
print('{} x {} = {}'.format(7, num, 7*num))
print('{} x {} = {}'.format(8, num, 8*num))
print('{} x {} = {}'.format(9, num, 9*num))
